### ISSUE TITLE
infinite loops on деп-related sentences

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-recursive#21] opened 2019-08-22 00:27 UTC
If you have a sentence like "Мен досум барам деп айттым." in a larger file, `rtx-proc` loops infinitely.

**Comment by mr-martian** [comment] 2019-08-22 00:49
@jonorthwash assuming such a sentence occurs in `texts/story.kir.txt`, the issue is actually with `lrx-proc` and appears to be a memory leak.

**Comment by mr-martian** [comment] 2019-08-22 01:32
Issue transferred to https://github.com/apertium/apertium-lex-tools/issues/29

**Closed** 2019-08-23 03:46 UTC
